### ISSUE TITLE
Emoji clashing on Lecturer Background

### ISSUE THREAD

**Issue by SunburntRock89** [t5r7/thomasr.me#5]
![image](https://github.com/itsmeimtom/thomasr.me/assets/29868053/4361c6e9-b669-4846-9dd7-9bba41952332)

**Comment by t5r7** [comment]
Suspect this is because the teacher emoji is made up of those two emojis, so devices that don't have the newer emoji fall back to the pair. Lazy fix will be to pick a different emoji.
